#!/usr/bin/env bash
# Convert a VS Code extension into a Tab Sage extension under build/<id>/.
#
# Usage:
#   ./transition.sh --vscode ../my-vscode-extension [options]
#
#   --vscode <dir>          Path to the VS Code extension folder (required).
#   --id <slug>             Override the derived id (^[a-z0-9-]+$).
#   --name <text>           Override the display name.
#   --description <text>    Override the description.
#   --author <text>         Override the author (defaults to "publisher").
#   --homepage <url>        Override the homepage.
#   --version <x.y.z>       Override the version.
#   --permissions p1,p2     Replace the inferred permission set.
#   --matches <pattern>     Match pattern (default "<all_urls>").
#   --run-at <when>         document_start | document_end (default document_end).
#   --entry <file>          Entry JS relative to --vscode (default: package.json "main").
#   --out <dir>             Output folder (default build/<id>).
#   --no-ui                 Do not vendor the Tab Sage UI Kit.
#   --force                 Overwrite an existing output folder.
#   -h, --help              Show this help.
#
# What it does:
#   Reads the VS Code package.json, derives a Tab Sage manifest.json from it,
#   lifts contributes.commands / contributes.keybindings / contributes.configuration
#   into runtime data, inlines the compiled JS, and emits a `vscode` compatibility
#   shim implemented on top of the `tabsage` host API. Simple extensions boot and
#   run; everything without a Tab Sage equivalent degrades to a loud stub that is
#   logged once and listed in the generated README.
#
# What it does not do:
#   It never runs npm. The extension must already be compiled: if package.json
#   "main" points at out/extension.js, run `npm install && npm run compile` in the
#   VS Code extension folder first. Tree views, editor decorations, language
#   servers, grammars, and debug adapters have no Tab Sage equivalent and are not
#   translated.
#
# The output in build/ is a starting point for review, not a finished extension.
# Read it, test it, then copy it to extensions/<id>/ when you are happy with it.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")" && pwd)"

usage() {
  sed -n '2,/^set -euo/p' "$0" | grep '^#' | sed 's/^# \{0,1\}//'
}

VSC_DIR="" ID="" NAME="" DESCRIPTION="" AUTHOR="" HOMEPAGE="" VERSION=""
PERMISSIONS="" MATCHES="" RUN_AT="" ENTRY="" OUT="" WITH_UI=1 FORCE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --vscode|--from) VSC_DIR="${2:-}"; shift 2 ;;
    --id) ID="${2:-}"; shift 2 ;;
    --name) NAME="${2:-}"; shift 2 ;;
    --description|--desc) DESCRIPTION="${2:-}"; shift 2 ;;
    --author) AUTHOR="${2:-}"; shift 2 ;;
    --homepage) HOMEPAGE="${2:-}"; shift 2 ;;
    --version) VERSION="${2:-}"; shift 2 ;;
    --permissions|--perms) PERMISSIONS="${2:-}"; shift 2 ;;
    --matches) MATCHES="${2:-}"; shift 2 ;;
    --run-at) RUN_AT="${2:-}"; shift 2 ;;
    --entry) ENTRY="${2:-}"; shift 2 ;;
    --out) OUT="${2:-}"; shift 2 ;;
    --ui) WITH_UI=1; shift ;;
    --no-ui) WITH_UI=0; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; echo >&2; usage >&2; exit 1 ;;
  esac
done

# --- preflight ---------------------------------------------------------------
if [ -z "$VSC_DIR" ]; then
  echo "Error: --vscode <dir> is required." >&2
  echo >&2
  usage >&2
  exit 1
fi
if ! command -v node >/dev/null 2>&1; then
  echo "Error: node (18 or newer) is required — the converter parses package.json with it." >&2
  exit 1
fi
if [ ! -d "$VSC_DIR" ]; then
  echo "Error: $VSC_DIR is not a directory." >&2
  exit 1
fi
if [ ! -f "$VSC_DIR/package.json" ]; then
  echo "Error: $VSC_DIR/package.json not found — that does not look like a VS Code extension." >&2
  exit 1
fi

case "${RUN_AT:-document_end}" in
  document_start|document_end) ;;
  *) echo "Error: --run-at must be document_start or document_end." >&2; exit 1 ;;
esac

# --- stage the static templates ----------------------------------------------
# They are written before the id is known, then moved into place by the Node
# step below (which is what derives the id from package.json).
stage="$(mktemp -d "${TMPDIR:-/tmp}/tabsage-transition.XXXXXX")"
trap 'rm -rf "$stage"' EXIT

cat > "$stage/vscode-shim.js" <<'SHIMJS'
// Generated by transition.sh — do not hand-edit unless you are done converting.
//
// A compatibility layer that implements enough of the VS Code extension API on
// top of the Tab Sage host API for a converted extension to boot in a content
// script. Anything with no Tab Sage equivalent becomes a stub: it logs once,
// records itself in window.__tsVscUnmapped, and returns another stub instead of
// throwing, so one missing API does not take the whole extension down.
(function (global) {
  if (global.__tsVscShimLoaded) return;
  global.__tsVscShimLoaded = true;

  // `tabsage` is an in-scope local in every content script, never window.tabsage.
  var T = typeof tabsage !== "undefined" ? tabsage : null;
  function ui() {
    return typeof TabSageUI !== "undefined" ? TabSageUI : null;
  }
  function noop() {}

  var unmapped = (global.__tsVscUnmapped = global.__tsVscUnmapped || []);
  var warned = {};
  function warnUnmapped(path) {
    if (warned[path]) return;
    warned[path] = true;
    unmapped.push(path);
    console.warn("[vscode-shim] unmapped: " + path);
  }

  // Properties that must never be faked: `then` in particular, because an
  // `await` on a stub would otherwise call it and hang forever.
  var NEVER_STUB = {
    then: 1,
    catch: 1,
    finally: 1,
    toJSON: 1,
    valueOf: 1,
    nodeType: 1,
    length: 1,
    name: 1,
    prototype: 1,
  };

  // Wraps a namespace so members the shim does not implement become logged
  // stubs instead of `undefined is not a function`.
  function withFallback(path, obj) {
    return new Proxy(obj, {
      get: function (target, prop) {
        if (prop in target) return target[prop];
        if (typeof prop === "symbol" || NEVER_STUB[prop]) return undefined;
        warnUnmapped(path + "." + String(prop));
        return stub(path + "." + String(prop));
      },
    });
  }

  function stub(path) {
    var target = function () {};
    return new Proxy(target, {
      get: function (t, prop) {
        if (typeof prop === "symbol") return undefined;
        if (NEVER_STUB[prop]) return undefined;
        return stub(path + "." + String(prop));
      },
      set: function () {
        return true;
      },
      apply: function () {
        warnUnmapped(path + "()");
        return stub(path + "()");
      },
      construct: function () {
        warnUnmapped("new " + path + "()");
        return stub(path + "()");
      },
    });
  }

  /* ── core value types ──────────────────────────────────────────────────── */

  function Disposable(fn) {
    this._dispose = typeof fn === "function" ? fn : noop;
  }
  Disposable.prototype.dispose = function () {
    try {
      this._dispose();
    } catch (e) {
      console.error("[vscode-shim] dispose failed", e);
    }
  };
  Disposable.from = function () {
    var all = [].slice.call(arguments);
    return new Disposable(function () {
      all.forEach(function (d) {
        if (d && typeof d.dispose === "function") d.dispose();
      });
    });
  };

  function EventEmitter() {
    var listeners = [];
    this.event = function (listener, thisArg) {
      var bound = thisArg ? listener.bind(thisArg) : listener;
      listeners.push(bound);
      return new Disposable(function () {
        var i = listeners.indexOf(bound);
        if (i >= 0) listeners.splice(i, 1);
      });
    };
    this.fire = function (value) {
      listeners.slice().forEach(function (l) {
        try {
          l(value);
        } catch (e) {
          console.error("[vscode-shim] event listener failed", e);
        }
      });
    };
    this.dispose = function () {
      listeners.length = 0;
    };
  }

  function deadEvent() {
    return new EventEmitter().event;
  }

  function Uri(scheme, authority, uriPath, query, fragment) {
    this.scheme = scheme || "file";
    this.authority = authority || "";
    this.path = uriPath || "";
    this.query = query || "";
    this.fragment = fragment || "";
    this.fsPath = this.path;
  }
  Uri.prototype.toString = function () {
    var s = this.scheme + "://" + this.authority + this.path;
    if (this.query) s += "?" + this.query;
    if (this.fragment) s += "#" + this.fragment;
    return s;
  };
  Uri.prototype.with = function (change) {
    change = change || {};
    return new Uri(
      change.scheme != null ? change.scheme : this.scheme,
      change.authority != null ? change.authority : this.authority,
      change.path != null ? change.path : this.path,
      change.query != null ? change.query : this.query,
      change.fragment != null ? change.fragment : this.fragment,
    );
  };
  Uri.file = function (p) {
    return new Uri("file", "", String(p));
  };
  Uri.parse = function (value) {
    var m = /^([a-z][a-z0-9+.-]*):\/\/([^/?#]*)([^?#]*)(?:\?([^#]*))?(?:#(.*))?$/i.exec(
      String(value),
    );
    if (!m) return new Uri("file", "", String(value));
    return new Uri(m[1], m[2] || "", m[3] || "", m[4] || "", m[5] || "");
  };
  Uri.joinPath = function (base) {
    var parts = [].slice.call(arguments, 1).join("/");
    var joined = String(base && base.path ? base.path : base).replace(/\/+$/, "");
    return (base && base.with ? base : Uri.file(joined)).with({
      path: joined + "/" + parts.replace(/^\/+/, ""),
    });
  };

  function Position(line, character) {
    this.line = line;
    this.character = character;
  }
  function Range(start, end) {
    if (typeof start === "number") {
      this.start = new Position(arguments[0], arguments[1]);
      this.end = new Position(arguments[2], arguments[3]);
    } else {
      this.start = start;
      this.end = end;
    }
    this.isEmpty = false;
  }
  function Selection(a, b, c, d) {
    Range.call(this, a, b, c, d);
    this.anchor = this.start;
    this.active = this.end;
  }
  Selection.prototype = Object.create(Range.prototype);

  function CancellationTokenSource() {
    var em = new EventEmitter();
    var self = this;
    this.token = {
      isCancellationRequested: false,
      onCancellationRequested: em.event,
    };
    this.cancel = function () {
      self.token.isCancellationRequested = true;
      em.fire();
    };
    this.dispose = function () {
      em.dispose();
    };
  }

  function ThemeIcon(id, color) {
    this.id = id;
    this.color = color;
  }
  ThemeIcon.File = new ThemeIcon("file");
  ThemeIcon.Folder = new ThemeIcon("folder");

  function ThemeColor(id) {
    this.id = id;
  }

  function MarkdownString(value) {
    this.value = value || "";
    this.isTrusted = false;
    this.appendText = function (v) {
      this.value += v;
      return this;
    };
    this.appendMarkdown = this.appendText;
    this.appendCodeblock = function (v, lang) {
      this.value += "\n```" + (lang || "") + "\n" + v + "\n```\n";
      return this;
    };
  }

  function TreeItem(label, collapsibleState) {
    if (label && label.path) {
      this.resourceUri = label;
      this.label = undefined;
    } else {
      this.label = label;
    }
    this.collapsibleState = collapsibleState || 0;
  }

  // VS Code labels can carry codicons like "$(sync~spin) Loading" — strip them
  // before anything user-visible.
  function plain(text) {
    return String(text == null ? "" : text)
      .replace(/\$\([a-z0-9~-]+\)/gi, "")
      .trim();
  }

  /* ── the shim factory ──────────────────────────────────────────────────── */

  // opts = { meta, state, persist }
  //   meta    the window.__TS_VSC block written by transition.sh
  //   state   { config, globalState, workspaceState, secrets } — prefetched by
  //           content.js so VS Code's synchronous config reads keep working
  //   persist called after every write; content.js debounces the actual save
  global.__tsVscCreateShim = function (opts) {
    opts = opts || {};
    var meta = opts.meta || {};
    var state = opts.state || {};
    var persist = typeof opts.persist === "function" ? opts.persist : noop;
    var label = meta.name || meta.id || "extension";

    state.config = state.config || {};
    state.globalState = state.globalState || {};
    state.workspaceState = state.workspaceState || {};
    state.secrets = state.secrets || {};

    var defaults = meta.configuration || {};
    var cfgEmitter = new EventEmitter();

    function clone(v) {
      if (v === null || typeof v !== "object") return v;
      try {
        return JSON.parse(JSON.stringify(v));
      } catch (e) {
        return v;
      }
    }

    function getConfiguration(section) {
      function full(key) {
        return section ? section + "." + key : key;
      }
      var api = {
        get: function (key, fallback) {
          var k = full(key);
          if (Object.prototype.hasOwnProperty.call(state.config, k))
            return state.config[k];
          if (Object.prototype.hasOwnProperty.call(defaults, k))
            return clone(defaults[k]);
          return fallback;
        },
        has: function (key) {
          var k = full(key);
          return (
            Object.prototype.hasOwnProperty.call(state.config, k) ||
            Object.prototype.hasOwnProperty.call(defaults, k)
          );
        },
        inspect: function (key) {
          var k = full(key);
          return {
            key: k,
            defaultValue: clone(defaults[k]),
            globalValue: state.config[k],
            workspaceValue: undefined,
          };
        },
        update: function (key, value) {
          var k = full(key);
          if (value === undefined) delete state.config[k];
          else state.config[k] = value;
          persist();
          cfgEmitter.fire({
            affectsConfiguration: function (s) {
              return k.indexOf(String(s)) === 0;
            },
          });
          return Promise.resolve();
        },
      };
      // Some extensions read settings as plain properties.
      Object.keys(defaults).forEach(function (k) {
        if (section && k.indexOf(section + ".") !== 0) return;
        var short = section ? k.slice(section.length + 1) : k;
        if (short.indexOf(".") >= 0 || api[short] !== undefined) return;
        Object.defineProperty(api, short, {
          enumerable: true,
          get: function () {
            return api.get(short);
          },
        });
      });
      return api;
    }

    function memento(bag) {
      return {
        get: function (key, fallback) {
          return Object.prototype.hasOwnProperty.call(bag, key)
            ? bag[key]
            : fallback;
        },
        update: function (key, value) {
          if (value === undefined) delete bag[key];
          else bag[key] = value;
          persist();
          return Promise.resolve();
        },
        keys: function () {
          return Object.keys(bag);
        },
        setKeysForSync: noop,
      };
    }

    /* ── window ──────────────────────────────────────────────────────────── */

    function notify(message) {
      var text = plain(message);
      if (T && T.notifications && T.notifications.show) {
        Promise.resolve(T.notifications.show(label, text)).catch(noop);
      }
      var U = ui();
      if (U) U.toast(text, { variant: "ok" });
      else if (!T || !T.notifications) console.log("[" + label + "] " + text);
    }

    function pick(title, entries) {
      // entries: [{ label, sublabel, value }] -> Promise<value | undefined>
      var U = ui();
      if (U) {
        return new Promise(function (resolve) {
          var done = false;
          var m = U.modal({
            title: title,
            body: U.list({
              items: entries.map(function (e) {
                return {
                  label: e.label,
                  sublabel: e.sublabel,
                  onClick: function () {
                    done = true;
                    m.close();
                    resolve(e.value);
                  },
                };
              }),
            }),
            onClose: function () {
              if (!done) resolve(undefined);
            },
          });
        });
      }
      if (T && T.dialogs && T.dialogs.prompt) {
        var lines = entries.map(function (e, i) {
          return i + 1 + ". " + e.label;
        });
        return Promise.resolve(
          T.dialogs.prompt(title + "\n" + lines.join("\n"), "1", label),
        ).then(function (answer) {
          var i = parseInt(answer, 10) - 1;
          return entries[i] ? entries[i].value : undefined;
        });
      }
      console.warn("[vscode-shim] cannot show a picker: no UI Kit, no dialogs permission");
      return Promise.resolve(undefined);
    }

    function showMessage(kind, args) {
      var message = args[0];
      var rest = args.slice(1);
      if (
        rest.length &&
        rest[0] &&
        typeof rest[0] === "object" &&
        !Array.isArray(rest[0]) &&
        ("modal" in rest[0] || "detail" in rest[0])
      ) {
        rest.shift();
      }
      var items = rest.length === 1 && Array.isArray(rest[0]) ? rest[0] : rest;
      if (kind === "error") console.error("[" + label + "] " + plain(message));
      else if (kind === "warn") console.warn("[" + label + "] " + plain(message));

      if (!items.length) {
        notify(message);
        return Promise.resolve(undefined);
      }
      var entries = items.map(function (it) {
        return {
          label: plain(typeof it === "string" ? it : it.title || String(it)),
          value: it,
        };
      });
      var U = ui();
      if (U) {
        return new Promise(function (resolve) {
          var answered;
          var m = U.modal({
            title: label,
            body: plain(message),
            actions: entries.map(function (e, i) {
              return {
                label: e.label,
                variant: i === 0 ? "primary" : "ghost",
                onClick: function () {
                  answered = e.value;
                  resolve(e.value);
                },
              };
            }),
            onClose: function () {
              if (answered === undefined) resolve(undefined);
            },
          });
          void m;
        });
      }
      if (entries.length === 1 && T && T.dialogs && T.dialogs.confirm) {
        return Promise.resolve(
          T.dialogs.confirm(plain(message), label),
        ).then(function (ok) {
          return ok ? entries[0].value : undefined;
        });
      }
      return pick(plain(message), entries);
    }

    function showInputBox(o) {
      o = o || {};
      var question = plain(o.prompt || o.placeHolder || o.title || "Input");
      if (T && T.dialogs && T.dialogs.prompt) {
        return Promise.resolve(
          T.dialogs.prompt(question, o.value || "", label),
        ).then(function (v) {
          return v == null ? undefined : v;
        });
      }
      var v = global.prompt ? global.prompt(question, o.value || "") : null;
      return Promise.resolve(v == null ? undefined : v);
    }

    function showQuickPick(items, o) {
      o = o || {};
      return Promise.resolve(items).then(function (list) {
        list = list || [];
        var entries = list
          .filter(function (it) {
            return !(it && it.kind === -1); // separators
          })
          .map(function (it) {
            return {
              label: plain(typeof it === "string" ? it : it.label),
              sublabel: plain(
                typeof it === "string" ? "" : it.description || it.detail || "",
              ),
              value: it,
            };
          });
        var title = plain(o.title || o.placeHolder || "Select");
        if (o.canPickMany) {
          warnUnmapped("window.showQuickPick({ canPickMany: true })");
          return pick(title, entries).then(function (v) {
            return v === undefined ? undefined : [v];
          });
        }
        return pick(title, entries);
      });
    }

    function createStatusBarItem() {
      var visible = false;
      var item = {
        id: "",
        alignment: 1,
        priority: 0,
        tooltip: "",
        command: undefined,
        color: undefined,
        backgroundColor: undefined,
        accessibilityInformation: undefined,
      };
      var text = "";
      function apply() {
        if (!T || !T.badge) return;
        if (visible && text) Promise.resolve(T.badge.set(plain(text))).catch(noop);
        else Promise.resolve(T.badge.clear()).catch(noop);
      }
      Object.defineProperty(item, "text", {
        enumerable: true,
        get: function () {
          return text;
        },
        set: function (v) {
          text = v == null ? "" : String(v);
          apply();
        },
      });
      item.show = function () {
        visible = true;
        apply();
      };
      item.hide = function () {
        visible = false;
        apply();
      };
      item.dispose = item.hide;
      return item;
    }

    function createOutputChannel(name) {
      var prefix = "[" + (name || label) + "]";
      function write(v) {
        console.log(prefix, v);
      }
      return {
        name: name,
        append: write,
        appendLine: write,
        replace: write,
        clear: noop,
        show: noop,
        hide: noop,
        dispose: noop,
      };
    }

    var WEBVIEW_PREAMBLE =
      "<script>window.acquireVsCodeApi=function(){var s;return{" +
      "postMessage:function(m){parent.postMessage(m,'*')}," +
      "getState:function(){return s},setState:function(v){s=v;return v}};};" +
      "</" +
      "script>";

    function createWebviewPanel(viewType, title, showOptions, options) {
      var U = ui();
      var messages = new EventEmitter();
      var disposed = new EventEmitter();
      var frame = document.createElement("iframe");
      frame.className = "ts-vsc-webview";
      frame.setAttribute("sandbox", "allow-scripts allow-forms allow-modals");
      frame.setAttribute("referrerpolicy", "no-referrer");

      var onMessage = function (e) {
        if (e.source === frame.contentWindow) messages.fire(e.data);
      };
      global.addEventListener("message", onMessage);

      var close;
      if (U) {
        var m = U.modal({
          title: plain(title),
          body: frame,
          onClose: function () {
            teardown();
          },
        });
        close = m.close;
      } else {
        warnUnmapped("window.createWebviewPanel (no UI Kit — rendering bare)");
        var box = document.createElement("div");
        box.className = "ts-vsc-webview-box";
        box.appendChild(frame);
        document.body.appendChild(box);
        close = function () {
          if (box.parentNode) box.parentNode.removeChild(box);
        };
      }

      var html = "";
      var webview = {
        options: options || {},
        cspSource: "",
        postMessage: function (msg) {
          try {
            frame.contentWindow.postMessage(msg, "*");
            return Promise.resolve(true);
          } catch (e) {
            return Promise.resolve(false);
          }
        },
        onDidReceiveMessage: messages.event,
        asWebviewUri: function (uri) {
          warnUnmapped("Webview.asWebviewUri (local resources are not bundled)");
          return uri;
        },
      };
      Object.defineProperty(webview, "html", {
        enumerable: true,
        get: function () {
          return html;
        },
        set: function (v) {
          html = String(v == null ? "" : v);
          frame.srcdoc = WEBVIEW_PREAMBLE + html;
        },
      });

      var alive = true;
      function teardown() {
        if (!alive) return;
        alive = false;
        global.removeEventListener("message", onMessage);
        disposed.fire();
      }

      return {
        viewType: viewType,
        title: title,
        webview: webview,
        visible: true,
        active: true,
        viewColumn: 1,
        options: showOptions,
        reveal: noop,
        onDidDispose: disposed.event,
        onDidChangeViewState: deadEvent(),
        dispose: function () {
          teardown();
          close();
        },
      };
    }

    function withProgress(options, task) {
      var title = plain((options && options.title) || "Working…");
      var U = ui();
      if (U) U.toast(title, { variant: "ok" });
      var progress = {
        report: function (v) {
          if (v && v.message) console.log("[" + label + "] " + plain(v.message));
        },
      };
      var token = new CancellationTokenSource().token;
      try {
        return Promise.resolve(task(progress, token));
      } catch (e) {
        return Promise.reject(e);
      }
    }

    /* ── commands ────────────────────────────────────────────────────────── */

    var commands = {};

    function registerCommand(id, callback, thisArg) {
      commands[id] = thisArg ? callback.bind(thisArg) : callback;
      return new Disposable(function () {
        delete commands[id];
      });
    }

    function executeCommand(id) {
      var args = [].slice.call(arguments, 1);
      var fn = commands[id];
      if (!fn) {
        console.warn("[vscode-shim] no command registered for id " + id);
        return Promise.resolve(undefined);
      }
      try {
        return Promise.resolve(fn.apply(null, args)).catch(function (e) {
          reportCommandError(id, e);
          return undefined;
        });
      } catch (e) {
        reportCommandError(id, e);
        return Promise.resolve(undefined);
      }
    }

    function reportCommandError(id, e) {
      console.error("[" + label + "] command " + id + " failed", e);
      var U = ui();
      if (U) U.toast(plain(id) + " failed — see the extension log", { variant: "danger" });
    }

    /* ── the vscode object ───────────────────────────────────────────────── */

    var base = {
      version: "1.85.0",

      window: {
        showInformationMessage: function () {
          return showMessage("info", [].slice.call(arguments));
        },
        showWarningMessage: function () {
          return showMessage("warn", [].slice.call(arguments));
        },
        showErrorMessage: function () {
          return showMessage("error", [].slice.call(arguments));
        },
        showInputBox: showInputBox,
        showQuickPick: showQuickPick,
        setStatusBarMessage: function (text) {
          notify(text);
          return new Disposable(noop);
        },
        createStatusBarItem: createStatusBarItem,
        createOutputChannel: createOutputChannel,
        createWebviewPanel: createWebviewPanel,
        withProgress: withProgress,
        showTextDocument: function () {
          warnUnmapped("window.showTextDocument");
          return Promise.resolve(undefined);
        },
        showOpenDialog: function () {
          warnUnmapped("window.showOpenDialog");
          return Promise.resolve(undefined);
        },
        showSaveDialog: function () {
          warnUnmapped("window.showSaveDialog");
          return Promise.resolve(undefined);
        },
        activeTextEditor: undefined,
        visibleTextEditors: [],
        activeTerminal: undefined,
        terminals: [],
        state: { focused: true },
        onDidChangeActiveTextEditor: deadEvent(),
        onDidChangeTextEditorSelection: deadEvent(),
        onDidChangeVisibleTextEditors: deadEvent(),
        onDidChangeWindowState: deadEvent(),
      },

      commands: {
        registerCommand: registerCommand,
        registerTextEditorCommand: registerCommand,
        executeCommand: executeCommand,
        getCommands: function () {
          return Promise.resolve(Object.keys(commands));
        },
      },

      workspace: {
        name: undefined,
        workspaceFolders: undefined,
        rootPath: undefined,
        textDocuments: [],
        getConfiguration: getConfiguration,
        onDidChangeConfiguration: cfgEmitter.event,
        onDidChangeWorkspaceFolders: deadEvent(),
        onDidOpenTextDocument: deadEvent(),
        onDidCloseTextDocument: deadEvent(),
        onDidChangeTextDocument: deadEvent(),
        onDidSaveTextDocument: deadEvent(),
        onDidCreateFiles: deadEvent(),
        onDidDeleteFiles: deadEvent(),
        onDidRenameFiles: deadEvent(),
        asRelativePath: function (p) {
          return String(p && p.path ? p.path : p);
        },
        getWorkspaceFolder: function () {
          return undefined;
        },
        createFileSystemWatcher: function () {
          return {
            onDidCreate: deadEvent(),
            onDidChange: deadEvent(),
            onDidDelete: deadEvent(),
            dispose: noop,
          };
        },
        findFiles: function () {
          warnUnmapped("workspace.findFiles");
          return Promise.resolve([]);
        },
        openTextDocument: function () {
          warnUnmapped("workspace.openTextDocument");
          return Promise.resolve(undefined);
        },
        applyEdit: function () {
          warnUnmapped("workspace.applyEdit");
          return Promise.resolve(false);
        },
        fs: stub("workspace.fs"),
      },

      env: {
        appName: "Tab Sage",
        appHost: "tabsage",
        uiKind: 1,
        language: (global.navigator && global.navigator.language) || "en",
        machineId: "tabsage",
        sessionId: "tabsage-session",
        isNewAppInstall: false,
        clipboard: {
          readText: function () {
            if (T && T.clipboard && T.clipboard.readText)
              return Promise.resolve(T.clipboard.readText());
            return Promise.reject(
              new Error("the 'clipboard' permission is not in manifest.json"),
            );
          },
          writeText: function (value) {
            if (T && T.clipboard && T.clipboard.writeText)
              return Promise.resolve(T.clipboard.writeText(String(value)));
            return Promise.reject(
              new Error("the 'clipboard' permission is not in manifest.json"),
            );
          },
        },
        openExternal: function (uri) {
          var url = String(uri && uri.toString ? uri.toString() : uri);
          if (T && T.tabs && T.tabs.open)
            return Promise.resolve(T.tabs.open(url)).then(function () {
              return true;
            });
          global.open(url, "_blank", "noopener");
          return Promise.resolve(true);
        },
        asExternalUri: function (uri) {
          return Promise.resolve(uri);
        },
      },

      extensions: {
        getExtension: function () {
          warnUnmapped("extensions.getExtension");
          return undefined;
        },
        all: [],
        onDidChange: deadEvent(),
      },

      // value types
      Uri: Uri,
      Disposable: Disposable,
      EventEmitter: EventEmitter,
      CancellationTokenSource: CancellationTokenSource,
      Position: Position,
      Range: Range,
      Selection: Selection,
      ThemeIcon: ThemeIcon,
      ThemeColor: ThemeColor,
      MarkdownString: MarkdownString,
      TreeItem: TreeItem,

      // enums the extension host would otherwise hand out
      StatusBarAlignment: { Left: 1, Right: 2 },
      ViewColumn: { Active: -1, Beside: -2, One: 1, Two: 2, Three: 3 },
      ConfigurationTarget: { Global: 1, Workspace: 2, WorkspaceFolder: 3 },
      ExtensionMode: { Production: 1, Development: 2, Test: 3 },
      ExtensionKind: { UI: 1, Workspace: 2 },
      ProgressLocation: { SourceControl: 1, Window: 10, Notification: 15 },
      QuickPickItemKind: { Separator: -1, Default: 0 },
      TreeItemCollapsibleState: { None: 0, Collapsed: 1, Expanded: 2 },
      UIKind: { Desktop: 1, Web: 2 },
      FileType: { Unknown: 0, File: 1, Directory: 2, SymbolicLink: 64 },
      DiagnosticSeverity: { Error: 0, Warning: 1, Information: 2, Hint: 3 },
      TextEditorRevealType: {
        Default: 0,
        InCenter: 1,
        InCenterIfOutsideViewport: 2,
        AtTop: 3,
      },
    };

    // Anything the shim does not implement resolves to a logged stub rather
    // than an undefined-property crash — at the top level and one level down,
    // which is where most of the API actually lives.
    ["window", "workspace", "commands", "env", "extensions"].forEach(function (ns) {
      base[ns] = withFallback("vscode." + ns, base[ns]);
    });

    var vscode = new Proxy(base, {
      get: function (target, prop) {
        if (prop in target) return target[prop];
        if (typeof prop === "symbol" || NEVER_STUB[prop]) return undefined;
        // tsc's __importStar/__importDefault helpers probe these first. Saying
        // "yes, an ES module" hands the live proxy straight through instead of
        // letting them copy it into a plain object and lose the stub fallback.
        if (prop === "__esModule") return true;
        if (prop === "default") return vscode;
        warnUnmapped(String(prop));
        return stub(String(prop));
      },
    });

    var secretsWarned = false;
    var secretsEmitter = new EventEmitter();

    var context = {
      subscriptions: [],
      extensionMode: 2,
      extensionPath: "/" + (meta.id || "extension"),
      extensionUri: Uri.file("/" + (meta.id || "extension")),
      globalState: memento(state.globalState),
      workspaceState: memento(state.workspaceState),
      globalStorageUri: Uri.file("/" + (meta.id || "extension") + "/storage"),
      storageUri: undefined,
      logUri: Uri.file("/" + (meta.id || "extension") + "/log"),
      environmentVariableCollection: stub("ExtensionContext.environmentVariableCollection"),
      extension: {
        id: meta.id,
        packageJSON: meta.packageJSON || {},
        extensionKind: 1,
        isActive: true,
      },
      asAbsolutePath: function (p) {
        return "/" + (meta.id || "extension") + "/" + String(p).replace(/^\.?\//, "");
      },
      secrets: {
        get: function (key) {
          warnSecrets();
          return Promise.resolve(state.secrets[key]);
        },
        store: function (key, value) {
          warnSecrets();
          state.secrets[key] = value;
          persist();
          secretsEmitter.fire({ key: key });
          return Promise.resolve();
        },
        delete: function (key) {
          warnSecrets();
          delete state.secrets[key];
          persist();
          secretsEmitter.fire({ key: key });
          return Promise.resolve();
        },
        onDidChange: secretsEmitter.event,
      },
    };

    function warnSecrets() {
      if (secretsWarned) return;
      secretsWarned = true;
      console.warn(
        "[vscode-shim] context.secrets is backed by tabsage.storage — it is NOT encrypted. Do not keep real credentials there.",
      );
    }

    return {
      vscode: vscode,
      context: context,
      executeCommand: executeCommand,
      commandIds: function () {
        return Object.keys(commands);
      },
    };
  };

  /* ── Node stand-ins ────────────────────────────────────────────────────── */

  // There is no Node runtime in a content script. `path` and `events` are pure
  // enough to reimplement, so extensions that only use those keep working;
  // everything else becomes a stub that logs when it is actually called rather
  // than exploding at require() time and taking the whole extension down.
  var NODE_MODULES = {};

  NODE_MODULES.path = (function () {
    function normalize(p) {
      var absolute = p.charAt(0) === "/";
      var out = [];
      p.split("/").forEach(function (part) {
        if (!part || part === ".") return;
        if (part === "..") {
          if (out.length && out[out.length - 1] !== "..") out.pop();
          else if (!absolute) out.push("..");
          return;
        }
        out.push(part);
      });
      return (absolute ? "/" : "") + out.join("/");
    }
    var api = {
      sep: "/",
      delimiter: ":",
      join: function () {
        return normalize([].slice.call(arguments).filter(Boolean).join("/")) || ".";
      },
      resolve: function () {
        var parts = [].slice.call(arguments).filter(Boolean);
        var joined = parts.join("/");
        return normalize(joined.charAt(0) === "/" ? joined : "/" + joined);
      },
      normalize: normalize,
      isAbsolute: function (p) {
        return String(p).charAt(0) === "/";
      },
      dirname: function (p) {
        var i = String(p).replace(/\/+$/, "").lastIndexOf("/");
        return i <= 0 ? (i === 0 ? "/" : ".") : String(p).slice(0, i);
      },
      basename: function (p, ext) {
        var b = String(p).replace(/\/+$/, "").split("/").pop() || "";
        if (ext && b.slice(-ext.length) === ext) b = b.slice(0, -ext.length);
        return b;
      },
      extname: function (p) {
        var b = api.basename(p);
        var i = b.lastIndexOf(".");
        return i > 0 ? b.slice(i) : "";
      },
      relative: function (from, to) {
        return normalize(String(to)).replace(normalize(String(from)) + "/", "");
      },
      parse: function (p) {
        return {
          root: api.isAbsolute(p) ? "/" : "",
          dir: api.dirname(p),
          base: api.basename(p),
          ext: api.extname(p),
          name: api.basename(p, api.extname(p)),
        };
      },
    };
    api.posix = api;
    api.win32 = api;
    return api;
  })();

  NODE_MODULES.events = (function () {
    function NodeEmitter() {
      this._events = {};
    }
    NodeEmitter.prototype.on = function (name, fn) {
      (this._events[name] = this._events[name] || []).push(fn);
      return this;
    };
    NodeEmitter.prototype.addListener = NodeEmitter.prototype.on;
    NodeEmitter.prototype.once = function (name, fn) {
      var self = this;
      function wrap() {
        self.off(name, wrap);
        fn.apply(null, arguments);
      }
      return this.on(name, wrap);
    };
    NodeEmitter.prototype.off = function (name, fn) {
      var list = this._events[name] || [];
      var i = list.indexOf(fn);
      if (i >= 0) list.splice(i, 1);
      return this;
    };
    NodeEmitter.prototype.removeListener = NodeEmitter.prototype.off;
    NodeEmitter.prototype.removeAllListeners = function (name) {
      if (name) delete this._events[name];
      else this._events = {};
      return this;
    };
    NodeEmitter.prototype.listeners = function (name) {
      return (this._events[name] || []).slice();
    };
    NodeEmitter.prototype.emit = function (name) {
      var args = [].slice.call(arguments, 1);
      var list = (this._events[name] || []).slice();
      list.forEach(function (fn) {
        try {
          fn.apply(null, args);
        } catch (e) {
          console.error("[vscode-shim] events listener failed", e);
        }
      });
      return list.length > 0;
    };
    NodeEmitter.EventEmitter = NodeEmitter;
    NodeEmitter.default = NodeEmitter;
    return NodeEmitter;
  })();

  NODE_MODULES.util = {
    promisify: function (fn) {
      return function () {
        var args = [].slice.call(arguments);
        return new Promise(function (resolve, reject) {
          args.push(function (err, value) {
            if (err) reject(err);
            else resolve(value);
          });
          fn.apply(null, args);
        });
      };
    },
    inspect: function (v) {
      try {
        return JSON.stringify(v);
      } catch (e) {
        return String(v);
      }
    },
    format: function () {
      return [].slice.call(arguments).join(" ");
    },
    types: { isPromise: function (v) { return !!v && typeof v.then === "function"; } },
  };

  var BUILTINS = {
    assert: 1, buffer: 1, child_process: 1, crypto: 1, dns: 1, events: 1,
    fs: 1, http: 1, https: 1, module: 1, net: 1, os: 1, path: 1, process: 1,
    readline: 1, stream: 1, string_decoder: 1, timers: 1, tls: 1, tty: 1,
    url: 1, util: 1, vm: 1, worker_threads: 1, zlib: 1,
  };

  // Node globals the module wrapper would normally provide.
  var NODE_PROCESS = {
    platform: "browser",
    arch: "wasm",
    version: "v18.0.0",
    versions: { node: "18.0.0" },
    env: {},
    argv: [],
    pid: 0,
    cwd: function () {
      return "/";
    },
    nextTick: function (fn) {
      Promise.resolve().then(fn);
    },
    on: noop,
    once: noop,
    off: noop,
    exit: noop,
    hrtime: function () {
      return [0, 0];
    },
  };

  global.__tsVscCreateLoader = function (vscode) {
    var mods = global.__tsVscModules || {};
    var cache = {};

    function dirname(key) {
      var i = key.lastIndexOf("/");
      return i < 0 ? "" : key.slice(0, i);
    }

    function normalize(base, id) {
      var out = [];
      (base ? base.split("/") : []).concat(id.split("/")).forEach(function (part) {
        if (!part || part === ".") return;
        if (part === "..") {
          out.pop();
          return;
        }
        out.push(part);
      });
      return out.join("/");
    }

    function resolve(fromKey, id) {
      var joined = normalize(dirname(fromKey), id.replace(/\.js$/, ""));
      var candidates = [joined, joined + "/index"];
      for (var i = 0; i < candidates.length; i++) {
        if (Object.prototype.hasOwnProperty.call(mods, candidates[i]))
          return candidates[i];
      }
      return null;
    }

    function requireFrom(fromKey, id) {
      if (id === "vscode") return vscode;
      var bare = String(id).replace(/^node:/, "");
      if (BUILTINS[bare]) {
        if (NODE_MODULES[bare]) return NODE_MODULES[bare];
        // No filesystem, no processes, no sockets in a page. Hand back a stub
        // so the extension still loads and only the code paths that need Node
        // misbehave — each one logs the first time it is called.
        warnUnmapped('require("' + bare + '")');
        NODE_MODULES[bare] = stub('require("' + bare + '")');
        return NODE_MODULES[bare];
      }
      if (id.charAt(0) !== ".") {
        throw new Error(
          'require("' +
            id +
            '") could not be resolved. Bundle node_modules into the entry file (e.g. esbuild --bundle --external:vscode) and convert that.',
        );
      }
      var key = resolve(fromKey, id);
      if (!key) {
        throw new Error(
          'require("' + id + '") from "' + fromKey + '" was not inlined by transition.sh.',
        );
      }
      return load(key);
    }

    function load(key) {
      if (Object.prototype.hasOwnProperty.call(cache, key))
        return cache[key].exports;
      var factory = mods[key];
      if (!factory) throw new Error('module "' + key + '" was not inlined.');
      var module = { exports: {}, id: key, loaded: false };
      cache[key] = module;
      factory(
        function (id) {
          return requireFrom(key, id);
        },
        module,
        module.exports,
        "/" + key + ".js",
        "/" + dirname(key),
        NODE_PROCESS,
        stub("Buffer"),
        global,
      );
      module.loaded = true;
      return module.exports;
    }

    return { load: load, has: function (key) { return !!mods[key]; } };
  };
})(window);
SHIMJS

cat > "$stage/content.js" <<'CONTENTJS'
// Generated by transition.sh — the bootstrap for a converted VS Code extension.
//
// Load order (see manifest.json): contributes.js -> vscode-shim.js ->
// extension.js -> this file. It restores saved state, builds the shim, runs the
// original module's activate(), then exposes the extension's commands through a
// Tab Sage launcher menu and keyboard shortcuts.
(function () {
  var meta = window.__TS_VSC;
  if (!meta) {
    console.error("[transition] contributes.js did not load — nothing to start.");
    return;
  }

  var guard = "__tsVsc_" + String(meta.id).replace(/[^A-Za-z0-9]/g, "_");
  if (window[guard]) return;
  window[guard] = true;

  var T = typeof tabsage !== "undefined" ? tabsage : null;
  var UI = typeof TabSageUI !== "undefined" ? TabSageUI : null;
  var STATE_KEY = "__vsc_state";

  var state = { config: {}, globalState: {}, workspaceState: {}, secrets: {} };
  var saveTimer = null;

  // tabsage.storage is async and VS Code's configuration reads are sync, so the
  // whole state bag is read once up front and written back on a short debounce.
  function persist() {
    if (!T || !T.storage || !T.storage.setJSON) return;
    if (saveTimer) clearTimeout(saveTimer);
    saveTimer = setTimeout(function () {
      saveTimer = null;
      Promise.resolve(T.storage.setJSON(STATE_KEY, state)).catch(function (e) {
        console.error("[" + meta.name + "] could not save state", e);
      });
    }, 250);
  }

  function loadState() {
    if (!T || !T.storage || !T.storage.getJSON) return Promise.resolve();
    return Promise.resolve(T.storage.getJSON(STATE_KEY))
      .then(function (saved) {
        if (!saved || typeof saved !== "object") return;
        ["config", "globalState", "workspaceState", "secrets"].forEach(function (k) {
          if (saved[k] && typeof saved[k] === "object") state[k] = saved[k];
        });
      })
      .catch(function (e) {
        console.warn("[" + meta.name + "] could not read saved state", e);
      });
  }

  function fail(what, e) {
    console.error("[" + meta.name + "] " + what, e);
    if (UI) UI.toast(meta.name + ": " + what, { variant: "danger" });
  }

  loadState().then(start);

  function start() {
    var shim;
    try {
      shim = window.__tsVscCreateShim({ meta: meta, state: state, persist: persist });
    } catch (e) {
      fail("could not build the vscode shim", e);
      return;
    }

    var loader = window.__tsVscCreateLoader(shim.vscode);
    var exports = null;
    try {
      exports = loader.load(meta.entry);
    } catch (e) {
      fail("could not load " + meta.entry + ".js", e);
      return;
    }

    if (exports && typeof exports.activate === "function") {
      try {
        Promise.resolve(exports.activate(shim.context)).catch(function (e) {
          fail("activate() rejected", e);
        });
      } catch (e) {
        fail("activate() threw", e);
      }
    } else {
      console.warn(
        "[" + meta.name + "] the converted module exports no activate(); commands may not be registered.",
      );
    }

    console.log(
      "[" + meta.name + "] converted extension ready on " + location.href,
    );

    wireLauncher(shim);
    wireShortcuts(shim);

    window.addEventListener("pagehide", function () {
      try {
        (shim.context.subscriptions || []).forEach(function (d) {
          if (d && typeof d.dispose === "function") d.dispose();
        });
        if (exports && typeof exports.deactivate === "function") exports.deactivate();
      } catch (e) {
        /* teardown is best effort */
      }
    });
  }

  // The VS Code command palette has no Tab Sage equivalent, so contributed
  // commands become a corner launcher menu.
  function wireLauncher(shim) {
    var commands = meta.commands || [];
    if (!commands.length) return;
    if (!UI) {
      console.warn(
        "[" + meta.name + "] the UI Kit is not loaded, so the command menu is unavailable. Run commands from other code with vscode.commands.executeCommand.",
      );
      return;
    }
    UI.launcher({
      label: meta.name,
      icon: "puzzle",
      corner: meta.corner || "bottom-right",
      title: meta.name + " commands",
      menu: commands.map(function (c) {
        return {
          label: c.category ? c.category + ": " + c.title : c.title,
          icon: "sparkle",
          onClick: function () {
            shim.executeCommand(c.command);
          },
        };
      }),
    });
  }

  function wireShortcuts(shim) {
    var keys = meta.keybindings || [];
    if (!keys.length || !T || !T.shortcuts || !T.shortcuts.register) return;
    keys.forEach(function (k) {
      try {
        T.shortcuts.register(k.accelerator, function () {
          shim.executeCommand(k.command);
        });
      } catch (e) {
        console.warn(
          "[" + meta.name + "] could not register " + k.accelerator + ": " + e.message,
        );
      }
    });
  }
})();
CONTENTJS

cat > "$stage/style.css" <<'STYLECSS'
/* Styles for the converted extension. The shim renders through the Tab Sage UI
   Kit, so these only cover the pieces the kit does not own. Keep selectors
   specific so the host page is unaffected. */

/* Webview panels are rendered as a sandboxed iframe inside a UI Kit modal. */
.ts-vsc-webview {
  display: block;
  width: 100%;
  min-width: 320px;
  min-height: 320px;
  border: 0;
  border-radius: 8px;
  background: #fff;
}

/* Fallback container used only when the UI Kit is not vendored. */
.ts-vsc-webview-box {
  position: fixed;
  right: 16px;
  bottom: 16px;
  z-index: 2147483646;
  width: 420px;
  max-width: calc(100vw - 32px);
  height: 420px;
  max-height: calc(100vh - 32px);
  padding: 8px;
  border-radius: 10px;
  background: #1b1b1f;
  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.35);
}
STYLECSS

# --- convert ------------------------------------------------------------------
TS_VSC_DIR="$VSC_DIR" \
TS_REPO="$repo_root" \
TS_STAGE="$stage" \
TS_ID="$ID" \
TS_NAME="$NAME" \
TS_DESC="$DESCRIPTION" \
TS_AUTHOR="$AUTHOR" \
TS_HOMEPAGE="$HOMEPAGE" \
TS_VERSION="$VERSION" \
TS_PERMS="$PERMISSIONS" \
TS_MATCHES="$MATCHES" \
TS_RUNAT="$RUN_AT" \
TS_ENTRY="$ENTRY" \
TS_OUT="$OUT" \
TS_UI="$WITH_UI" \
TS_FORCE="$FORCE" \
TS_CWD="$PWD" \
node - <<'CONVERTMJS'
"use strict";
const fs = require("fs");
const path = require("path");

const env = process.env;
const VSC = path.resolve(env.TS_CWD, env.TS_VSC_DIR);
const REPO = env.TS_REPO;
const STAGE = env.TS_STAGE;
const WITH_UI = env.TS_UI === "1";
const FORCE = env.TS_FORCE === "1";

// Same list the PR validator enforces (.github/scripts/validate-pr.mjs).
const KNOWN_PERMISSIONS = [
  "content_scripts", "storage", "ai", "tabs", "notifications", "dialogs",
  "adblock", "cutout", "clipboard", "downloads", "badge", "messaging",
];
const ID_RE = /^[a-z0-9-]+$/;
const VERSION_RE = /^\d+\.\d+\.\d+$/;

const notes = [];
const warnings = [];
const blockers = [];

function die(msg) {
  console.error("Error: " + msg);
  process.exit(1);
}
function warn(msg) {
  warnings.push(msg);
  console.error("Warning: " + msg);
}

/* ── read the VS Code manifest ─────────────────────────────────────────────── */

let pkg;
try {
  pkg = JSON.parse(fs.readFileSync(path.join(VSC, "package.json"), "utf8"));
} catch (e) {
  die("could not parse " + path.join(VSC, "package.json") + ": " + e.message);
}
if (!pkg.engines || !pkg.engines.vscode) {
  warn("package.json has no engines.vscode — converting it anyway, but check that this is really a VS Code extension.");
}

function slug(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/^@[^/]+\//, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const id = env.TS_ID || slug(pkg.name);
if (!ID_RE.test(id)) {
  die(
    'could not derive a valid id from package.json name "' + (pkg.name || "") +
      '". Pass one explicitly: --id my-extension',
  );
}

function normalizeVersion(v) {
  const core = String(v || "").split(/[-+]/)[0];
  const parts = core.split(".").filter((p) => /^\d+$/.test(p));
  while (parts.length < 3) parts.push("0");
  return parts.slice(0, 3).join(".");
}
const version = env.TS_VERSION || normalizeVersion(pkg.version || "1.0.0");
if (!VERSION_RE.test(version)) {
  die('version "' + version + '" is not MAJOR.MINOR.PATCH. Pass --version 1.0.0.');
}
if (pkg.version && version !== pkg.version && !env.TS_VERSION) {
  notes.push('version "' + pkg.version + '" was normalized to "' + version + '".');
}

const name = env.TS_NAME || pkg.displayName || pkg.name || id;
const description =
  env.TS_DESC ||
  pkg.description ||
  "Converted from the VS Code extension " + (pkg.name || id) + ".";

function deriveAuthor() {
  if (env.TS_AUTHOR) return env.TS_AUTHOR;
  if (pkg.publisher) return pkg.publisher;
  if (typeof pkg.author === "string") return pkg.author.replace(/\s*<.*$/, "").trim();
  if (pkg.author && pkg.author.name) return pkg.author.name;
  return "Unknown";
}
const author = deriveAuthor();

function deriveHomepage() {
  if (env.TS_HOMEPAGE) return env.TS_HOMEPAGE;
  if (pkg.homepage) return pkg.homepage;
  const repo = pkg.repository;
  const url = typeof repo === "string" ? repo : repo && repo.url;
  if (!url) return null;
  return String(url).replace(/^git\+/, "").replace(/\.git$/, "");
}
const homepage = deriveHomepage() || null;

const matches = env.TS_MATCHES || "<all_urls>";
const runAt = env.TS_RUNAT || "document_end";

/* ── find the compiled entry ───────────────────────────────────────────────── */

const mainField = pkg.main ? String(pkg.main) : "";
const candidates = env.TS_ENTRY
  ? [env.TS_ENTRY]
  : [mainField, "out/extension.js", "dist/extension.js", "extension.js"].filter(Boolean);

let entryAbs = null;
for (const c of candidates) {
  const rel = String(c).replace(/^\.\//, "");
  const p = path.resolve(VSC, rel);
  if (fs.existsSync(p) && fs.statSync(p).isFile()) {
    entryAbs = p;
    break;
  }
}
if (!entryAbs) {
  const hint = mainField
    ? 'package.json main is "' + mainField + '", which does not exist.'
    : "no main field and no out/extension.js, dist/extension.js, or extension.js.";
  die(
    "compiled entry not found: " + hint +
      "\n  transition.sh never runs npm. Build the extension first, e.g.:" +
      "\n    (cd " + env.TS_VSC_DIR + " && npm install && npm run compile)" +
      "\n  then re-run, or point at a file directly with --entry dist/extension.js",
  );
}
if (!/\.js$/.test(entryAbs)) {
  die("the entry must be JavaScript, not " + path.extname(entryAbs) + " — compile it first.");
}

/* ── collect the modules to inline ─────────────────────────────────────────── */

const entryDir = path.dirname(entryAbs);
const SKIP_DIRS = new Set([
  "node_modules", ".git", ".vscode", ".vscode-test", "test", "tests",
  "__tests__", "coverage", "media", "images", "icons",
]);
const SKIP_FILES = new Set(["package.json", "package-lock.json", "tsconfig.json", "jsconfig.json"]);
const MAX_FILES = 400;
const MAX_BYTES = 8 * 1024 * 1024;

const modules = [];
let totalBytes = 0;

function walk(dir) {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (e) {
    return;
  }
  for (const ent of entries) {
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      if (SKIP_DIRS.has(ent.name) || ent.name.startsWith(".")) continue;
      walk(abs);
      continue;
    }
    if (!ent.isFile()) continue;
    if (SKIP_FILES.has(ent.name)) continue;
    if (/\.(test|spec)\.js$/.test(ent.name)) continue;
    if (!/\.(js|json)$/.test(ent.name)) continue;
    const rel = path.relative(entryDir, abs).split(path.sep).join("/");
    const key = rel.replace(/\.js$/, "");
    const source = fs.readFileSync(abs, "utf8");
    totalBytes += Buffer.byteLength(source);
    modules.push({ key, rel, abs, source, json: /\.json$/.test(ent.name) });
  }
}
walk(entryDir);

if (!modules.length) die("no JavaScript found next to " + entryAbs + ".");
if (modules.length > MAX_FILES) {
  die(
    modules.length + " files would be inlined from " + entryDir +
      ". Bundle the extension (esbuild --bundle --external:vscode) and convert the bundle with --entry.",
  );
}
if (totalBytes > MAX_BYTES) {
  die(
    Math.round(totalBytes / 1024) + " KB of JavaScript would be inlined. Bundle and minify the extension first.",
  );
}
if (totalBytes > 1024 * 1024) {
  warn(Math.round(totalBytes / 1024) + " KB of JavaScript inlined — that is a lot to inject into every page.");
}

const entryKey = path
  .relative(entryDir, entryAbs)
  .split(path.sep)
  .join("/")
  .replace(/\.js$/, "");

/* ── static scan: permissions, unmapped APIs, blockers ─────────────────────── */

const allSource = modules.map((m) => m.source).join("\n");

const PERMISSION_HINTS = [
  ["clipboard", /env\s*\.\s*clipboard|\.clipboard\s*\.\s*(readText|writeText)/],
  ["notifications", /show(Information|Warning|Error)Message|setStatusBarMessage|withProgress/],
  ["dialogs", /showInputBox|showQuickPick|showOpenDialog|showSaveDialog/],
  ["storage", /getConfiguration|globalState|workspaceState|\bsecrets\b|Memento/],
  ["tabs", /openExternal|showTextDocument|tabGroups/],
  ["badge", /createStatusBarItem/],
];

let permissions;
if (env.TS_PERMS) {
  permissions = env.TS_PERMS.split(",").map((p) => p.trim()).filter(Boolean);
} else {
  permissions = ["content_scripts"];
  for (const [perm, re] of PERMISSION_HINTS) {
    if (re.test(allSource) && permissions.indexOf(perm) < 0) permissions.push(perm);
  }
}
if (permissions.indexOf("content_scripts") < 0) permissions.unshift("content_scripts");
for (const p of permissions) {
  if (KNOWN_PERMISSIONS.indexOf(p) < 0) {
    die('unknown permission "' + p + '". Valid: ' + KNOWN_PERMISSIONS.join(", ") + ".");
  }
}

const UNMAPPED_HINTS = [
  ["languages.*  (completions, hovers, diagnostics)", /\blanguages\s*\./],
  ["debug.*  (debug adapters)", /\bdebug\s*\.\s*(start|register|active)/],
  ["tasks.*  (task providers)", /\btasks\s*\.\s*(register|execute|fetch)/],
  ["window.activeTextEditor  (no editor in a browser page)", /activeTextEditor/],
  ["window.createTreeView / TreeDataProvider", /createTreeView|registerTreeDataProvider/],
  ["window.registerWebviewViewProvider  (sidebar views)", /registerWebviewViewProvider/],
  ["window.createTerminal", /createTerminal/],
  ["workspace.fs / findFiles / applyEdit  (no filesystem)", /workspace\s*\.\s*(fs|findFiles|applyEdit)/],
  ["workspace.openTextDocument", /openTextDocument/],
];
const unmapped = UNMAPPED_HINTS.filter(([, re]) => re.test(allSource)).map(([label]) => label);

const BUILTIN_RE = /require\(\s*["'](?:node:)?(fs|path|os|child_process|http|https|net|crypto|stream|zlib|worker_threads|readline|tls|dns|vm|events|util|url|assert|buffer)["']\s*\)/g;
const builtins = new Set();
let bm;
while ((bm = BUILTIN_RE.exec(allSource))) builtins.add(bm[1]);
// path, events, and util are reimplemented by the shim; the rest have nothing
// to stand on in a page and become stubs that do nothing.
const POLYFILLED = new Set(["path", "events", "util"]);
const stubbedBuiltins = [...builtins].filter((b) => !POLYFILLED.has(b)).sort();
const polyfilledBuiltins = [...builtins].filter((b) => POLYFILLED.has(b)).sort();
if (stubbedBuiltins.length) {
  blockers.push(
    "the code requires Node built-ins that do not exist in a content script: " +
      stubbedBuiltins.join(", ") +
      ". They resolve to stubs that log and do nothing, so every code path through them is dead until you replace it.",
  );
}
if (polyfilledBuiltins.length) {
  notes.push(
    "require(" + polyfilledBuiltins.join("), require(") + ") is served by the shim's own browser implementation.",
  );
}

const bareRequires = new Set();
const BARE_RE = /require\(\s*["']([^."'][^"']*)["']\s*\)/g;
let rm;
while ((rm = BARE_RE.exec(allSource))) {
  const mod = rm[1].replace(/^node:/, "");
  if (mod === "vscode" || builtins.has(mod)) continue;
  bareRequires.add(mod);
}
if (bareRequires.size) {
  blockers.push(
    "the code requires npm packages that were not inlined: " +
      [...bareRequires].sort().join(", ") +
      ". Bundle them (esbuild --bundle --external:vscode) and convert the bundle with --entry.",
  );
}

/* ── contributes ───────────────────────────────────────────────────────────── */

const contributes = pkg.contributes || {};

function asArray(v) {
  if (!v) return [];
  return Array.isArray(v) ? v : [v];
}

const commands = asArray(contributes.commands).map((c) => ({
  command: c.command,
  title: c.title || c.command,
  category: c.category || "",
})).filter((c) => c.command);

const MOD_MAP = {
  ctrl: "Ctrl", control: "Ctrl", cmd: "Cmd", meta: "Cmd", win: "Cmd", super: "Cmd",
  alt: "Alt", option: "Alt", shift: "Shift",
};

function accelerator(key, mac) {
  if (!key) return null;
  if (/\s/.test(String(key).trim())) return null; // chords are unsupported
  const winParts = String(key).split("+").map((p) => p.trim().toLowerCase());
  const macParts = mac && !/\s/.test(String(mac).trim())
    ? String(mac).split("+").map((p) => p.trim().toLowerCase())
    : null;

  const out = [];
  const seen = {};
  winParts.forEach((part, i) => {
    const isLast = i === winParts.length - 1;
    if (!isLast && MOD_MAP[part]) {
      // ctrl on Windows + cmd on macOS is exactly what Mod means.
      if (part === "ctrl" || part === "control") {
        const macHasCmd = macParts && macParts.some((p) => p === "cmd" || p === "meta");
        out.push(macHasCmd ? "Mod" : "Ctrl");
      } else {
        out.push(MOD_MAP[part]);
      }
      seen[part] = 1;
      return;
    }
    if (isLast) out.push(part.length === 1 ? part.toUpperCase() : titleKey(part));
  });
  if (out.length < 2) return null; // a bare key would fight the page
  return out.join("+");
}

function titleKey(k) {
  const special = {
    enter: "Enter", escape: "Escape", esc: "Escape", space: "Space", tab: "Tab",
    backspace: "Backspace", delete: "Delete", up: "Up", down: "Down",
    left: "Left", right: "Right", home: "Home", end: "End",
  };
  if (special[k]) return special[k];
  if (/^f\d{1,2}$/.test(k)) return k.toUpperCase();
  return k;
}

const keybindings = [];
const droppedKeys = [];
asArray(contributes.keybindings).forEach((k) => {
  if (!k || !k.command) return;
  const accel = accelerator(k.key, k.mac);
  if (!accel) {
    droppedKeys.push((k.key || "?") + " → " + k.command);
    return;
  }
  keybindings.push({ command: k.command, accelerator: accel });
});

const configuration = {};
asArray(contributes.configuration).forEach((block) => {
  const props = (block && block.properties) || {};
  Object.keys(props).forEach((key) => {
    configuration[key] = props[key] && props[key].default !== undefined
      ? props[key].default
      : undefined;
  });
});

const droppedContributes = Object.keys(contributes).filter(
  (k) => ["commands", "keybindings", "configuration"].indexOf(k) < 0,
);
if (droppedContributes.length) {
  notes.push("contributes." + droppedContributes.join(", contributes.") + " has no Tab Sage equivalent and was dropped.");
}
if (pkg.activationEvents && pkg.activationEvents.length) {
  notes.push(
    "activationEvents (" + pkg.activationEvents.join(", ") +
      ") were dropped — a Tab Sage content script always runs, at " + runAt + ".",
  );
}

/* ── output folder ─────────────────────────────────────────────────────────── */

const outDir = env.TS_OUT
  ? path.resolve(env.TS_CWD, env.TS_OUT)
  : path.join(REPO, "build", id);

if (fs.existsSync(outDir)) {
  if (!FORCE) die(outDir + " already exists. Re-run with --force to replace it.");
  const looksOurs =
    fs.existsSync(path.join(outDir, "manifest.json")) ||
    fs.readdirSync(outDir).length === 0;
  if (!looksOurs) {
    die(outDir + " exists but has no manifest.json — refusing to delete it. Pick another --out.");
  }
  fs.rmSync(outDir, { recursive: true, force: true });
}
fs.mkdirSync(outDir, { recursive: true });

const registryDir = path.join(REPO, "extensions", id);
if (fs.existsSync(registryDir)) {
  warn('extensions/' + id + ' already exists in this repo. Publishing an update needs a version above the one already there.');
  try {
    const existing = JSON.parse(fs.readFileSync(path.join(registryDir, "manifest.json"), "utf8"));
    if (existing.version && cmpVersion(existing.version, version) >= 0) {
      warn("extensions/" + id + " is at version " + existing.version + " — bump past it with --version.");
    }
  } catch (e) {
    /* nothing published yet */
  }
}

function cmpVersion(a, b) {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < 3; i++) {
    if ((pa[i] || 0) !== (pb[i] || 0)) return (pa[i] || 0) - (pb[i] || 0);
  }
  return 0;
}

/* ── write the extension ───────────────────────────────────────────────────── */

for (const f of ["vscode-shim.js", "content.js", "style.css"]) {
  fs.copyFileSync(path.join(STAGE, f), path.join(outDir, f));
}

let hasUi = WITH_UI;
if (WITH_UI) {
  const kit = path.join(REPO, "ui-kit", "dist", "tabsage-ui.min.js");
  if (fs.existsSync(kit)) {
    fs.copyFileSync(kit, path.join(outDir, "tabsage-ui.js"));
  } else {
    hasUi = false;
    warn(
      "ui-kit/dist/tabsage-ui.min.js not found, so the UI Kit was not vendored. Build it with `node ui-kit/build.mjs` and re-run; menus and pickers fall back to dialogs until then.",
    );
  }
}

// contributes.js — the declarative half of the VS Code manifest, as data.
const vscMeta = {
  id,
  name,
  entry: entryKey,
  commands,
  keybindings,
  configuration,
  packageJSON: {
    name: pkg.name,
    displayName: pkg.displayName,
    version: pkg.version,
    publisher: pkg.publisher,
    description: pkg.description,
    contributes: { commands },
  },
};
fs.writeFileSync(
  path.join(outDir, "contributes.js"),
  "// Generated by transition.sh — the declarative parts of the VS Code manifest.\n" +
    "// contributes.commands become launcher menu items, contributes.keybindings\n" +
    "// become tabsage.shortcuts, contributes.configuration supplies setting defaults.\n" +
    "window.__TS_VSC = " +
    JSON.stringify(vscMeta, null, 2) +
    ";\n",
);

// extension.js — every source file in Node's own module wrapper, so `require`,
// `module`, and `exports` stay module-local instead of leaking onto the page.
function stripSource(source) {
  return source
    .replace(/^#!.*\n/, "")
    .replace(/^\/\/# sourceMappingURL=.*$/gm, "")
    .replace(/\s+$/, "");
}

const WRAPPER_ARGS =
  "require, module, exports, __filename, __dirname, process, Buffer, global";

let bundle =
  "// Generated by transition.sh from " + path.relative(VSC, entryAbs).split(path.sep).join("/") +
  " in " + (pkg.name || id) + " " + (pkg.version || "") + ".\n" +
  "// Each module keeps Node's module wrapper so require/module/exports stay\n" +
  "// local — defining them globally would break host pages that UMD-sniff them.\n" +
  "window.__tsVscModules = window.__tsVscModules || {};\n\n";

for (const m of modules) {
  bundle += "window.__tsVscModules[" + JSON.stringify(m.key) + "] = function (" + WRAPPER_ARGS + ") {\n";
  bundle += m.json
    ? "module.exports = " + m.source.trim() + ";"
    : stripSource(m.source);
  bundle += "\n};\n\n";
}
fs.writeFileSync(path.join(outDir, "extension.js"), bundle);

// manifest.json — same key order as `tabsage new`.
const js = [];
if (hasUi) js.push("tabsage-ui.js");
js.push("contributes.js", "vscode-shim.js", "extension.js", "content.js");

const manifest = {
  id,
  name,
  version,
  description,
  author,
  homepage,
  permissions,
  content_scripts: [{ matches: [matches], js, css: ["style.css"], run_at: runAt }],
};
fs.writeFileSync(path.join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");

/* ── README with the conversion report ────────────────────────────────────── */

function bullets(list) {
  return list.length ? list.map((l) => "- " + l).join("\n") : "- None.";
}

const readme = [
  "# " + name,
  "",
  description,
  "",
  "Converted from the VS Code extension `" + (pkg.name || id) + "` " +
    (pkg.version ? "(" + pkg.version + ") " : "") + "by `transition.sh`.",
  "",
  "## What it touches",
  "",
  "- Runs on: `" + matches + "` at `" + runAt + "` (never in incognito).",
  "- State (settings, globalState, workspaceState) lives under one `tabsage.storage` key, `__vsc_state`.",
  "- Review this section by hand before publishing: describe what the extension actually reads or changes.",
  "",
  "## Permissions",
  "",
  permissions.map((p) => "`" + p + "`").join(", ") +
    ". (`page`, `runtime`, and `shortcuts` need no permission.)",
  "",
  "## Commands",
  "",
  commands.length
    ? commands.map((c) => "- **" + (c.category ? c.category + ": " : "") + c.title + "** — `" + c.command + "`").join("\n")
    : "- None contributed.",
  "",
  "## Conversion notes",
  "",
  "- Entry: `" + path.relative(VSC, entryAbs).split(path.sep).join("/") + "` (" + modules.length +
    " module" + (modules.length === 1 ? "" : "s") + " inlined, " + Math.round(totalBytes / 1024) + " KB).",
  "- Commands mapped to launcher menu items: " + commands.length + ".",
  "- Keybindings mapped to `tabsage.shortcuts`: " +
    (keybindings.length ? keybindings.map((k) => "`" + k.accelerator + "` → `" + k.command + "`").join(", ") : "none") + ".",
  droppedKeys.length
    ? "- Keybindings dropped (chords and bare keys are unsupported): " + droppedKeys.map((k) => "`" + k + "`").join(", ") + "."
    : "- No keybindings were dropped.",
  "",
  "### Blockers",
  "",
  bullets(blockers),
  "",
  "### VS Code APIs with no Tab Sage equivalent",
  "",
  "These were found in the source and resolve to logged stubs at runtime. Check",
  "`window.__tsVscUnmapped` in a page where the extension ran for the live list.",
  "",
  bullets(unmapped),
  "",
  "### Dropped from the VS Code manifest",
  "",
  bullets(notes),
  "",
  warnings.length ? "### Warnings\n\n" + bullets(warnings) + "\n" : "",
  "### Before publishing",
  "",
  "- [ ] Load it unpacked in Tab Sage and exercise every command.",
  "- [ ] Replace stubbed APIs, or delete the code paths that need them.",
  "- [ ] Rewrite this README to describe the extension, not the conversion.",
  "- [ ] Copy the folder to `extensions/" + id + "/` and open one PR for it.",
  "",
  "## Changes",
  "",
  "- " + version + " — Initial release.",
  "",
].join("\n");
fs.writeFileSync(path.join(outDir, "README.md"), readme.replace(/\n{3,}/g, "\n\n"));

/* ── validate exactly like the PR validator would ─────────────────────────── */

const problems = [];
if (!ID_RE.test(manifest.id)) problems.push('id "' + manifest.id + '" must match ^[a-z0-9-]+$');
if (manifest.id !== path.basename(outDir) && !env.TS_OUT) {
  problems.push("id must equal the folder name");
}
if (!VERSION_RE.test(manifest.version)) problems.push("version must be MAJOR.MINOR.PATCH");
for (const field of ["name", "description", "author"]) {
  if (typeof manifest[field] !== "string" || !manifest[field].trim()) {
    problems.push(field + " must be a non-empty string");
  }
}
for (const p of manifest.permissions) {
  if (KNOWN_PERMISSIONS.indexOf(p) < 0) problems.push('unknown permission "' + p + '"');
}
for (const entry of manifest.content_scripts) {
  if (!entry.matches || !entry.matches.length) problems.push("content_scripts needs matches");
  if (["document_start", "document_end"].indexOf(entry.run_at) < 0) {
    problems.push('run_at must be document_start or document_end');
  }
  for (const rel of [].concat(entry.js || [], entry.css || [])) {
    if (rel.startsWith("/") || rel.includes("..") || rel.includes(":")) {
      problems.push('"' + rel + '" must be a relative path inside the extension');
    } else if (!fs.existsSync(path.join(outDir, rel))) {
      problems.push('"' + rel + '" is referenced but missing');
    }
  }
}
if (problems.length) {
  console.error("Error: the generated manifest is invalid:");
  problems.forEach((p) => console.error("  - " + p));
  process.exit(1);
}

/* ── report ───────────────────────────────────────────────────────────────── */

const rel = path.relative(env.TS_CWD, outDir) || outDir;
console.log("Converted " + (pkg.name || id) + " " + (pkg.version || "") + " → " + rel);
console.log("  manifest ok  id=" + id + "  version=" + version);
console.log("  permissions  " + permissions.join(", "));
console.log("  modules      " + modules.length + " inlined (" + Math.round(totalBytes / 1024) + " KB)");
console.log("  commands     " + commands.length + " → launcher menu");
console.log("  keybindings  " + keybindings.length + " mapped" + (droppedKeys.length ? ", " + droppedKeys.length + " dropped" : ""));
console.log("  ui kit       " + (hasUi ? "vendored" : "not vendored"));
if (unmapped.length) {
  console.log("  unmapped     " + unmapped.length + " VS Code API area(s) — see README.md");
}
if (blockers.length) {
  console.log("");
  blockers.forEach((b) => console.log("  BLOCKER: " + b));
}
CONVERTMJS

echo
echo "Next steps:"
echo "  1. Read the Conversion notes in the generated README.md."
echo "  2. In Tab Sage: Settings > Extensions > Load unpacked → the folder printed above."
echo "  3. Reload a page it matches, then check Settings > Extensions > Activity for stub warnings."
echo "  4. When it works, copy the folder to extensions/<id>/ and open one pull request for it."
